name: Deploy Vue Build
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build dist
      run: |
        export FIREBASE_KEY="${{ secrets.FIREBASE_KEY }}"
        yarn
        yarn build
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.0
      with:
        switches: -avz --no-perms --delete .
        path: 'dist/'
        remote_path: trivia.andyflick.com
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}